-- AlterTable
ALTER TABLE `colaborador` MODIFY `NOMBRE` VARCHAR(191) NOT NULL DEFAULT 45,
    MODIFY `APELLIDO` VARCHAR(191) NOT NULL DEFAULT 45,
    MODIFY `DIRECCION` VARCHAR(191) NOT NULL DEFAULT 45,
    MODIFY `EDAD` INTEGER NOT NULL DEFAULT 3,
    MODIFY `PROFESION` VARCHAR(191) NOT NULL DEFAULT 45,
    MODIFY `ESTADOCIVIL` VARCHAR(191) NOT NULL DEFAULT 45;
